### PR TITLE
Reduce MSRV for Tier 1 platforms to 1.31

### PR DESCRIPTION
**Pull request by Kijewski**

### CODE REVIEW

**Comment by astraw** [comment]
LGTM. Do you want to make a release with this and #58, or shall I? We could also attempt to test minimum versions in CI.

**Comment by Kijewski** [comment]
> We could also attempt to test minimum versions in CI.

I'm testing this right now: https://github.com/Kijewski/iana-time-zone/actions/runs/3039445259/jobs/4894387642. :) I just need to rebase onto this PR, then I'll the PR. When that one is merge, so was release the next version.

**Comment by astraw** [comment]
OK, I just published 1.48 with the changes from today. Thanks @Kijewski and @djc!

**Comment by djc** [comment]
Thanks for all the work on this, great turnaround time!

**Pull request merged**
