### PR TITLE
Bump version number to 0.1.59

### PR DESCRIPTION
**Pull request by Kijewski**

### CODE REVIEW

**Comment by Kijewski** [comment]
Netbsd currently does not cross-compile correctly, but that is unrelated to this PR or #125.

**Review by astraw — APPROVED** [review]
It looks good to me. (Although I haven't checked this on Windows as I'm not using that OS much at the moment and this is the only OS with changes. Still, I don't see much potential for problems.)

**Comment by astraw** [comment]
@Kijewski would you like to do the honors of publishing this?

**Comment by Kijewski** [comment]
Sure! Released as 0.1.59. Guten Rutsch in advance! :)

**Pull request merged**
